name: "Process SARIF file"
description: "Process SARF file into GitHub annotations."

branding:
  icon: package
  color: black

inputs:
  sarif_file:
    description: "SARIF file to process"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.sarif_file }}
